Document: giteapanel-2019.05.11
Title: Debian giteapanel-2019.05.11 Manual
Author: <insert document author here>
Abstract: This manual describes what giteapanel-2019.05.11 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/giteapanel-2019.05.11/giteapanel-2019.05.11.sgml.gz

Format: postscript
Files: /usr/share/doc/giteapanel-2019.05.11/giteapanel-2019.05.11.ps.gz

Format: text
Files: /usr/share/doc/giteapanel-2019.05.11/giteapanel-2019.05.11.text.gz

Format: HTML
Index: /usr/share/doc/giteapanel-2019.05.11/html/index.html
Files: /usr/share/doc/giteapanel-2019.05.11/html/*.html
